version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: todo_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=johndoe123
    volumes:
      - ./pgdata:/var/lib/postgresql/data
